services:
  database:
    image: postgres:12
    environment:
      POSTGRES_USER: quarto
      POSTGRES_PASSWORD: quarto
      POSTGRES_DB: quarto
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - target: 80
        published: 5000
        protocol: tcp
        mode: host
    depends_on:
      - database
      - redis
    environment:
      - POSTGRES_USER=quarto
      - POSTGRES_PASSWORD=quarto
      - POSTGRES_HOST=database
      - POSTGRES_DB=quarto
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=no
      - SMTP_PASSWORD=no
      - SMTP_DISPLAYNAME=no
      - FRONT_URL=https://quarto.fr
      - LOG_LEVEL=debug
      - LISTEN_PORT=80
      - MAX_BODY_SIZE=20M

volumes:
  database:
